routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Blog of Hung

Route::get('/','Blog\HomeController@index')->name('home');
Route::get('page/{slug}','Blog\PageController@index')->name('page');
Route::get('post/{category}','Blog\PostController@index')->name('post');
Route::get('post/{category}/{slug}','Blog\PostController@show')->name('post.show');

app/CategoryPost.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CategoryPost extends Model
{
	protected $guarded = ['id'];

    public function user(){
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

app/Menu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
	protected $guarded = ['id'];

    public function user(){
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function parent()
    {
        return $this->belongsTo(Menu::class,'parent_id');
    }
}

app/Page.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Page extends Model
{
	protected $guarded = ['id'];

    public function user(){
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

app/Post.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
	protected $guarded = ['id'];

    public function category(){
        return $this->belongsTo(CategoryPost::class, 'category_id', 'id');
    }

    public function user(){
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function getCreatedAtAttribute($value)
	{
		return Carbon::create($value)->diffForHumans();
	}
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Blog/HomeController.php
<?php

namespace App\Http\Controllers\Blog;

use App\CategoryPost;
use App\Helpers\Constants;
use App\Post;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
	/**
	 * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
	 */
	public function index(){
//		Project
    	$category_project = CategoryPost::where('slug', Constants::PROJECTS)->firstOrFail();
    	$projects = Post::where('category_id', $category_project->id)->take(3)->get();
		if (count($projects) > 0){
			$result = [];
			foreach ($projects as $project){
				$project->skills = explode(',', $project->skills);
				$result[] = $project;
			}
			$projects = $result;
		}
//		Post
		$category_post = CategoryPost::where('slug', Constants::BLOG)->firstOrFail();
		$posts = Post::where('category_id', $category_post->id)->take(3)->get();
    	return view('blog.home.index', compact('category_post', 'category_project', 'projects', 'posts'));
	}
}

app/Http/Controllers/Blog/PageController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Page;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PageController extends Controller
{
    public function index($slug){
    	$page = Page::where('slug', $slug)->firstOrFail();
    	if($page->slug === 'cv'){
			return view('blog.page.cv', compact('page'));
		}
    	return view('blog.page.index', compact('page'));
	}
}

app/Http/Controllers/Blog/PostController.php
<?php

namespace App\Http\Controllers\Blog;

use App\CategoryPost;
use App\Post;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($category)
    {
		$category = CategoryPost::where('slug',$category)->firstOrFail();
		$posts = Post::where('category_id', $category->id)->get();
		if ($category->slug === 'projects'){
			if (count($posts) > 0){
				$result = [];
				foreach ($posts as $post){
					$post->skills = explode(',', $post->skills);
					$result[] = $post;
				}
				$posts = $result;
			}
			return view('blog.post.project.index', compact('posts', 'category'));
		}elseif ($category->slug === 'talks'){
			return view('blog.post.talk.index', compact('posts', 'category'));
		}
		return view('blog.post.blog.index', compact('posts', 'category'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($category, $slug)
    {
		$category = CategoryPost::where('slug',$category)->firstOrFail();
		$post = Post::where('slug', $slug)->firstOrFail();
		$posts_related = Post::where('category_id', $category->id)->where('slug','!=', Request::segment(3))->take(3)->get();
		$posts_project_related = Post::where('category_id', $category->id)->where('slug','!=', Request::segment(3))->take(3)->get();
		if (count($posts_project_related) > 0){
			$result = [];
			foreach ($posts_project_related as $post){
				$post->skills = explode(',', $post->skills);
				$result[] = $post;
			}
			$posts_project_related = $result;
		}
		if ($category->slug === 'projects'){
			return view('blog.post.project.detail', compact('post', 'category', 'posts_project_related'));
		}elseif ($category->slug === 'talks'){
			return view('blog.post.talk.detail', compact('post', 'category', 'posts_related'));
		}
		return view('blog.post.blog.detail', compact('post', 'category', 'posts_related'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/blog/page/cv.blade.php
@extends('blog.layout')
@section('title')
    {{ $page->title }}
@endsection
@section('css')
    style="
    min-height: 10vh !important; 
    background-size: cover;
{{--    background-position: 0px 10px;--}}
    background-image: url('{{ asset("storage/$page->header_background")}}') !important;"
@endsection
@section('header')
<div style="opacity: 1;transform: translateY(0px) translateZ(0px); margin: 10px 0px;">
    <div class="header-intro header-intro-resume text-white py-5">
        <div class="container position-relative text-center">
            <h2 class="page-heading mb-3">{{ $page->title }}</h2>
{{--            <a class="btn theme-btn-on-bg download-resume position-absolute font-weight-bold mx-auto" href="https://themes.3rdwavemedia.com/resources/sketch-template/pillar-sketch-sketch-resume-template-for-developers/" target="_blank"><svg class="svg-inline--fa fa-download fa-w-16 mr-2" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="download" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M216 0h80c13.3 0 24 10.7 24 24v168h87.7c17.8 0 26.7 21.5 14.1 34.1L269.7 378.3c-7.5 7.5-19.8 7.5-27.3 0L90.1 226.1c-12.6-12.6-3.7-34.1 14.1-34.1H192V24c0-13.3 10.7-24 24-24zm296 376v112c0 13.3-10.7 24-24 24H24c-13.3 0-24-10.7-24-24V376c0-13.3 10.7-24 24-24h146.7l49 49c20.1 20.1 52.5 20.1 72.6 0l49-49H488c13.3 0 24 10.7 24 24zm-124 88c0-11-9-20-20-20s-20 9-20 20 9 20 20 20 20-9 20-20zm64 0c0-11-9-20-20-20s-20 9-20 20 9 20 20 20 20-9 20-20z"></path></svg><!-- <i class="fas fa-download mr-2"></i> -->Download PDF Version</a>--}}
        </div><!--//container-->
    </div>
</div>
   
@endsection
@section('content')
    {!! $page->body !!}
@endsection

resources/views/blog/page/index.blade.php
@extends('blog.layout')
@section('title')
    {{ $page->title }}
@endsection
@section('css')
    style="min-height: 50vh !important; 
    background-size: cover; 
     background-image: url('{{ asset("storage/$page->header_background")}}') !important;"
@endsection
@section('header')
<div style="opacity: 1;transform: translateY(0px) translateZ(0px); margin: 50px 0px;">
    <div class="header-intro text-white py-5">
        <div class="container text-center">
            <h2 class="page-heading mb-0">{{ $page->title }}</h2>
        </div><!--//container-->
    </div>
</div>
@endsection
@section('content')
    <section class="section py-5">
        <div class="container">
            {!! $page->body !!}
        </div><!--//container-->
    </section>
@endsection

resources/views/blog/partials/footer.blade.php
<div style="background-color: #536976;">
    <section class="section-cta py-4 text-white">
        <div class="container">
            <div class="text-center">
                <img class="profile-small d-inline-block mx-auto rounded-circle mb-2" src="{{ asset('blog/index/profile.jpg') }}" alt="">
            </div>
            <h3 class="section-title font-weight-bold text-center mb-2">{{ trans('home.client_project') }}</h3>
            <div class="section-intro mx-auto text-center mb-3">
                {{ trans('home.contact_one') }} <a href="{{ route('page', 'contact') }}" style="color: #ace6fd">{{ trans('home.contact_two') }}</a>
            </div>
        </div><!--//container-->
    </section>
    <footer class=" text-light text-center py-2">
        <small class="copyright">{{ trans('home.development') }}</small>
    </footer>
</div>

resources/views/blog/post/blog/detail.blade.php
@extends('blog.layout')
@section('title')
    {{ $category->title }}
@endsection
@section('css')
    style="min-height: 50vh !important; 
    background-size: cover; 
    background-image: url('{{ asset("storage/$post->header_background")}}') !important;"
@endsection
@section('header')
<div style="opacity: 1;transform: translateY(0px) translateZ(0px); margin: 50px 0px;">
    <div class="header-intro text-white py-5">
        <div class="container text-center">
            <h2 class="page-heading mb-2">{{ $post->title }}</h2>
            <div class="page-heading mb-2" style="font-size: 20px">{{ $post->header_description }}</div>
        </div><!--//container-->
    </div>
</div>
@endsection
@section('content')
    <section class="single-post-wrapper single-col-max-width py-5 px-4 mx-auto">
        <div class="section-row">
            {!! $post->body !!}
        </div>
    </section>
    <section class="section pt-5 related-projects-section bg-white">
        <div class="container">
            <h3 class="section-title font-weight-bold text-center mb-4">{{ trans('home.post_relate_blog')}}</h3>
            
            <div class="blog-cards blog-cards-related">
                <div class="project-cards row">
                    @if(count($posts_related) > 0)
                        @foreach($posts_related as $item)
                        <div class="col-12 col-lg-4 mb-5">
                            <div class="card rounded-0 border-0 shadow-sm eq-height">
                                <div class="card-img-container position-relative">
                                    <img class="card-img-top rounded-0" src="{{ asset("storage/$item->image") }}" alt="">
                                    <div class="card-img-overlay overlay-mask  text-center p-0">
                                        {{--  <div class="overlay-mask-content text-center w-100 position-absolute">
                                            <a class="btn btn-primary" href="blog-post.html">Read more</a>
                                        </div>  --}}
                                        <a class="overlay-mask-link position-absolute w-100 h-100" href="{{ route('post.show', [$category->slug, $post->slug]) }}"></a>
                                    </div>
                                </div>
                                <div class="card-body pb-4">

                                    <h4 class="card-title mb-2"><a href="{{ route('post.show', [$category->slug, $post->slug]) }}">{{$item->title}}</a></h4>
                                    <div class="card-text">

                                        <div class="excerpt">{{$item->description}}</div>
                                    </div>
                                </div>
                                <div class="card-footer border-0">
                                    <ul class="meta list-inline mb-0">
                                        <li class="list-inline-item mr-2"><svg class="svg-inline--fa fa-clock fa-w-16 mr-2" aria-hidden="true" focusable="false" data-prefix="far" data-icon="clock" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm0 448c-110.5 0-200-89.5-200-200S145.5 56 256 56s200 89.5 200 200-89.5 200-200 200zm61.8-104.4l-84.9-61.7c-3.1-2.3-4.9-5.9-4.9-9.7V116c0-6.6 5.4-12 12-12h32c6.6 0 12 5.4 12 12v141.7l66.8 48.6c5.4 3.9 6.5 11.4 2.6 16.8L334.6 349c-3.9 5.3-11.4 6.5-16.8 2.6z"></path></svg><!-- <i class="far fa-clock mr-2"></i> -->{{ $item->created_at}}</li>
                                        {{--  <li class="list-inline-item"><svg class="svg-inline--fa fa-comment fa-w-16 mr-2" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="comment" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M256 32C114.6 32 0 125.1 0 240c0 49.6 21.4 95 57 130.7C44.5 421.1 2.7 466 2.2 466.5c-2.2 2.3-2.8 5.7-1.5 8.7S4.8 480 8 480c66.3 0 116-31.8 140.6-51.4 32.7 12.3 69 19.4 107.4 19.4 141.4 0 256-93.1 256-208S397.4 32 256 32z"></path></svg><!-- <i class="fas fa-comment mr-2"></i> --><a href="#">63 Comments</a></li>  --}}
                                    </ul>
                                </div>
                            </div><!--//card-->
                        </div>
                        @endforeach
                    @endif
                </div><!--//row-->
            </div>

        </div><!--//container-->
    </section>
@endsection

resources/views/blog/post/blog/index.blade.php
@extends('blog.layout')
@section('title')
    {{ $category->title }}
@endsection
@section('css')
    style="min-height: 50vh !important; 
    background-size: cover; 
    background-image: url('{{ asset("storage/$category->header_background")}}') !important;"
@endsection
@section('header')
<div style="opacity: 1;transform: translateY(0px) translateZ(0px); margin: 50px 0px;">
    <div class="header-intro text-white py-5">
        <div class="container text-center">
            <h2 class="page-heading mb-2">{{ $category->title }}</h2>
            <div class="page-heading mb-2" style="font-size: 20px">{{ $category->header_description }}</div>
        </div><!--//container-->
    </div>
</div>
@endsection
@section('content')
    <section class="section pt-5">
        <div class="container blog-cards">

            <div class="row">
                @if(count($posts) > 0)
                    @foreach($posts as $post)
                        <div class="col-12 col-md-6 col-lg-4 mb-5">
                            <div class="card rounded-0 border-0 shadow-sm eq-height">
                                <div class="card-img-container position-relative">
                                    <img class="card-img-top rounded-0" style="height: 180px;" src="{{ asset("storage/$post->image") }}" alt="">
                                    <div class="card-img-overlay overlay-mask text-center p-0">
                                        {{--  <div class="overlay-mask-content text-center w-100 position-absolute">
                                            <a class="btn btn-primary" href="{{ route('post.show', [$category->slug, $post->slug]) }}">Đọc th</a>
                                        </div>  --}}
                                        <a class="overlay-mask-link position-absolute w-100 h-100" href="{{ route('post.show', [$category->slug, $post->slug]) }}"></a>
                                    </div>
                                </div>
                                <div class="card-body pb-4">

                                    <h4 class="card-title mb-2"><a href="{{ route('post.show', [$category->slug, $post->slug]) }}">{{ $post->title }}</a></h4>
                                    <div class="card-text">

                                        <div class="excerpt">{{ $post->description }}</div>
                                    </div>

                                </div>
                                <div class="card-footer border-0">
                                    <ul class="meta list-inline mb-0">
                                        <li class="list-inline-item mr-3"><svg class="svg-inline--fa fa-clock fa-w-16 mr-2" aria-hidden="true" focusable="false" data-prefix="far" data-icon="clock" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm0 448c-110.5 0-200-89.5-200-200S145.5 56 256 56s200 89.5 200 200-89.5 200-200 200zm61.8-104.4l-84.9-61.7c-3.1-2.3-4.9-5.9-4.9-9.7V116c0-6.6 5.4-12 12-12h32c6.6 0 12 5.4 12 12v141.7l66.8 48.6c5.4 3.9 6.5 11.4 2.6 16.8L334.6 349c-3.9 5.3-11.4 6.5-16.8 2.6z"></path></svg><!-- <i class="far fa-clock mr-2"></i> -->{{ $post->created_at }}</li>
                                        {{--<li class="list-inline-item"><svg class="svg-inline--fa fa-comment fa-w-16 mr-2" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="comment" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M256 32C114.6 32 0 125.1 0 240c0 49.6 21.4 95 57 130.7C44.5 421.1 2.7 466 2.2 466.5c-2.2 2.3-2.8 5.7-1.5 8.7S4.8 480 8 480c66.3 0 116-31.8 140.6-51.4 32.7 12.3 69 19.4 107.4 19.4 141.4 0 256-93.1 256-208S397.4 32 256 32z"></path></svg><!-- <i class="fas fa-comment mr-2"></i> --><a href="#">12 Comments</a></li>--}}
                                    </ul>
                                </div>
                            </div><!--//card-->
                        </div>
                    @endforeach
                @endif
                {{--  <div class="col-12 mb-5">
                    <a class="btn-blog-more btn btn-primary btn-block text-white font-weight-bold">Load more posts...</a>
                </div>  --}}
            </div>
        </div><!--//container-->
    </section>
@endsection

resources/views/blog/post/talk/detail.blade.php
@extends('blog.layout')
@section('title')
    {{ $post->title }}
@endsection
@section('css')
    style="min-height: 50vh !important; 
    background-size: cover; 
    background-image: url('{{ asset("storage/$post->header_background")}}') !important;"
@endsection
@section('header')
<div style="opacity: 1;transform: translateY(0px) translateZ(0px); margin: 50px 0px;">
    <div class="header-intro text-white py-5">
        <div class="container text-center">
            <h2 class="page-heading mb-2">{{ $post->title }}</h2>
            <div class="page-heading mb-2" style="font-size: 20px">{{ $post->header_description }}</div>
        </div><!--//container-->
    </div>
</div>
@endsection
@section('content')
    <section class="single-post-wrapper single-col-max-width py-5 px-4 mx-auto">
        <div class="section-row">
            {!! $post->body !!}
        </div>
    </section>
    <section class="section pt-5 related-projects-section bg-white">
        <div class="container">
            <h3 class="section-title font-weight-bold text-center mb-4">{{ trans('home.post_relate_blog') }}</h3>
            <div class="blog-cards blog-cards-related">
                <div class="row">
                    @if(count($posts_related) > 0)
                        @foreach($posts_related as $item)
                            <div class="col-12 col-lg-4 mb-5">
                                <div class="card rounded-0 border-0 shadow-sm eq-height">
                                    <div class="card-img-container position-relative">
                                        <img class="card-img-top rounded-0" src="{{ asset("storage/$item->image") }}" alt="">
                                        <div class="card-img-overlay overlay-mask  text-center p-0">
                                            {{--  <div class="overlay-mask-content text-center w-100 position-absolute">
                                                <a class="btn btn-primary" href="blog-post.html">Read more</a>
                                            </div>  --}}
                                            <a class="overlay-mask-link position-absolute w-100 h-100" href="{{ route('post.show', [$category->slug, $post->slug]) }}"></a>
                                        </div>
                                    </div>
                                    <div class="card-body pb-4">

                                        <h4 class="card-title mb-2"><a href="{{ route('post.show', [$category->slug, $post->slug]) }}">{{$item->title}}</a></h4>
                                        <div class="card-text">

                                            <div class="excerpt">{{$item->description}}</div>
                                        </div>
                                    </div>
                                    <div class="card-footer border-0">
                                        <ul class="meta list-inline mb-0">
                                            <li class="list-inline-item mr-2"><svg class="svg-inline--fa fa-clock fa-w-16 mr-2" aria-hidden="true" focusable="false" data-prefix="far" data-icon="clock" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm0 448c-110.5 0-200-89.5-200-200S145.5 56 256 56s200 89.5 200 200-89.5 200-200 200zm61.8-104.4l-84.9-61.7c-3.1-2.3-4.9-5.9-4.9-9.7V116c0-6.6 5.4-12 12-12h32c6.6 0 12 5.4 12 12v141.7l66.8 48.6c5.4 3.9 6.5 11.4 2.6 16.8L334.6 349c-3.9 5.3-11.4 6.5-16.8 2.6z"></path></svg><!-- <i class="far fa-clock mr-2"></i> -->{{ $item->created_at}}</li>
                                            {{--  <li class="list-inline-item"><svg class="svg-inline--fa fa-comment fa-w-16 mr-2" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="comment" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M256 32C114.6 32 0 125.1 0 240c0 49.6 21.4 95 57 130.7C44.5 421.1 2.7 466 2.2 466.5c-2.2 2.3-2.8 5.7-1.5 8.7S4.8 480 8 480c66.3 0 116-31.8 140.6-51.4 32.7 12.3 69 19.4 107.4 19.4 141.4 0 256-93.1 256-208S397.4 32 256 32z"></path></svg><!-- <i class="fas fa-comment mr-2"></i> --><a href="#">63 Comments</a></li>  --}}
                                        </ul>
                                    </div>
                                </div><!--//card-->
                            </div>
                        @endforeach
                    @endif
                </div><!--//row-->
            </div>

        </div><!--//container-->
    </section>
@endsection

resources/views/blog/post/talk/index.blade.php
@extends('blog.layout')
@section('title')
    {{ $category->title }}
@endsection
@section('css')
    style="min-height: 50vh !important; 
    background-size: cover; 
    background-image: url('{{ asset("storage/$category->header_background")}}') !important;"
@endsection
@section('header')
<div style="opacity: 1;transform: translateY(0px) translateZ(0px); margin: 50px 0px;">
    <div class="header-intro text-white py-5">
        <div class="container text-center">
            <h2 class="page-heading mb-2">{{ $category->title }}</h2>
            <div class="page-heading mb-2" style="font-size: 20px">{{ $category->header_description }}</div>
        </div><!--//container-->
    </div>
</div>
@endsection
@section('content')
    <section class="section pt-5">
        <div class="container">
            @if(count($posts) > 0)
                @foreach($posts as $post)
                    <div class="media mb-5 flex-column flex-lg-row bg-white shadow-sm">
                        <div class="talk-media-holder embed-responsive embed-responsive-16by9 mr-md-3">
                            <iframe class="embed-responsive-item" width="560" height="315" src="{{ $post->link_youtube }}" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>
                        </div>

                        <div class="media-body p-4">
                            <h4> <a href="{{ route('post.show',[$category->slug, $post->slug]) }}">{{ $post->title }}</a></h4>
                            <div class="talk-content">
                                <p>{{ $post->description }}</p>
                            </div>
                            <ul class="talk-meta list-inline mb-2">
                                <li class="list-inline-item mr-3"><svg class="svg-inline--fa fa-clock fa-w-16 mr-2" aria-hidden="true" focusable="false" data-prefix="far" data-icon="clock" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm0 448c-110.5 0-200-89.5-200-200S145.5 56 256 56s200 89.5 200 200-89.5 200-200 200zm61.8-104.4l-84.9-61.7c-3.1-2.3-4.9-5.9-4.9-9.7V116c0-6.6 5.4-12 12-12h32c6.6 0 12 5.4 12 12v141.7l66.8 48.6c5.4 3.9 6.5 11.4 2.6 16.8L334.6 349c-3.9 5.3-11.4 6.5-16.8 2.6z"></path></svg><!-- <i class="far fa-clock mr-2"></i> -->{{ $post->created_at }}</li>
                                <li class="list-inline-item"><svg class="svg-inline--fa fa-video fa-w-18 mr-2" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="video" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" data-fa-i2svg=""><path fill="currentColor" d="M336.2 64H47.8C21.4 64 0 85.4 0 111.8v288.4C0 426.6 21.4 448 47.8 448h288.4c26.4 0 47.8-21.4 47.8-47.8V111.8c0-26.4-21.4-47.8-47.8-47.8zm189.4 37.7L416 177.3v157.4l109.6 75.5c21.2 14.6 50.4-.3 50.4-25.8V127.5c0-25.4-29.1-40.4-50.4-25.8z"></path></svg><!-- <i class="fas fa-video mr-2"></i> -->Video</li>
                            </ul>
                        </div>
                    </div><!--//media-->
                @endforeach
            @endif
        </div><!--//container-->
    </section>
@endsection